config/routes.rb
Rails.application.routes.draw do
  get 'syllabuses/create'

  get 'home/index'

  devise_for :users
  resources :courses do
    resources :syllabuses
  end
  resources :chapters

  root 'home#index'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :syllabus
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :syllabuses
end

app/models/syllabus.rb
class Syllabus < ActiveRecord::Base
  belongs_to :course
  has_many :chapters
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :role, :email, :password, :password_confirmation)
    end
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController


  def index
    @syllabus = Syllabus.find(params[:format])
    @chapters = @syllabus.chapters
  end

  def new
    @chapter = Chapter.new
    @syllabus = Syllabus.find(params[:format])
  end

  def create
    @syllabus = Syllabus.find(params[:chapter][:syllabus_id])
    @chapter = @syllabus.chapters.create(chapter_params)
    #redirect_to course_path(@course)
    redirect_to courses_path
  end

  private
    def chapter_params
      params.require(:chapter).permit(:name)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    @course.save
    puts "========================"
    puts @course.inspect
    puts "========================"
    redirect_to courses_path
  end

  def show
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/syllabuses_controller.rb
class SyllabusesController < ApplicationController

  def index
    @syllabuses = Syllabus.all
  end

  def create
    @course = Course.find(params[:course_id])
    @syllabus = @course.syllabuses.create(syllabus_params)
    redirect_to course_path(@course)
  end

  def show
    raise params.inspect
  end

  private
    def syllabus_params
      params.require(:syllabus).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/syllabuses_helper.rb
module SyllabusesHelper
end

app/views/chapters/index.html.erb
<div style="padding-top:20px;margin-left:183px;">
  <h2>Listing Chapter</h2><br /><br />
  <% if @chapters.present? %>
  <table>
    <tr>
      <th>Chapter</th>
    </tr>

    <% @chapters.each do |chapter| %>
      <tr>
        <td><%= chapter.name %></td>
      </tr>
    <% end %>
  </table><br />
  <% end %>
  <%= link_to 'Back', courses_path %>
</div>

app/views/chapters/new.html.erb
<div style="padding-top:20px;margin-left:183px;">
  <h2> New Chapter </h2>
  <%= form_for(@chapter) do |f| %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <%= f.hidden_field :syllabus_id, value: @syllabus.id %>

    <p>
      <%= f.submit "create", class: "btn btn-success" %>
    </p>
  <% end %>
</div>

app/views/courses/index.html.erb
<div style="padding-top:20px;margin-left:183px;">
  <h2>Listing Courses</h2><br /><br />
  <% if @courses.present? %>
  <table>
    <tr>
      <th>Course</th>
      <th>Links</th>
    </tr>

    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to "Show", course_path(course) %> &nbsp||
        <%= link_to "Syllabus", course_syllabuses_path(course) %></td>
      </tr>
    <% end %>
  </table><br />
  <% if current_user.role == "professor" %>
    <%= link_to 'New course', new_course_path, class: "btn btn-primary" %>
  <% end %>
  <% else %>
  <b>No Courses</b><br />
  <% if current_user.role == "professor" %>
    <%= link_to 'New course', new_course_path %>
  <% end %>
  <% end %>
</div>

app/views/courses/new.html.erb
<div style="padding-top:20px;margin-left:183px;">
  <%= form_for(@course) do |f| %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>


    <p>
      <%= f.submit "create", class: "btn btn-success"  %>
    </p>
  <% end %>
</div>

app/views/courses/show.html.erb
<div style="padding-top:20px;margin-left:183px;" class="container">
  <p>
    <strong>Title:</strong>
    <%= @course.name %>
  </p><br />


  <h2>Syllabuses</h2>
  <% @course.syllabuses.each do |syllabus| %>
    <p>
      <strong>Name:</strong>
      <%= syllabus.name %>
    </p>

  <% end %>
  <br /><br />
  <% if current_user.role == "professor" %>
    <h2>Add a Syllabus:</h2>
    <%= form_for([@course, @course.syllabuses.build]) do |f| %>
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.submit "Create", class: "btn btn-success" %>
      </p>
    <% end %>
  <% end %>

  <br />
  <%= link_to 'Back', courses_path, class: "btn btn-primary" %>
</div>

app/views/home/index.html.erb
<div style="padding-top:20px;margin-left:183px;">
  <h1>Edutest</h1>
  <p>Education test</p>
</div>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom" style="background-color: #0039A0;border: none;">
    <div class="container">
      <p style="color:white;margin-left:120px;" class="navbar-text">© Copyright reserved | Privacy Policy</p>

      <p style="color:white;float:right;margin-top:15px;margin-right:102px;">
        Made at &nbsp&nbsp<a href="http://inquirly.com/" target="_blank" >Inquirly</a>
      </p>
    </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="row">
    <div class='navbar nav nav-list navbar-fixed-top' style ='background-color: #0039A0; height:72px; border: none;'>
      <div style="margin-left:190px;padding-top:3px;color:white;" class='col-lg-2 col-md-2 logo-div'>
           <h2> Edutest App </h2>
       </div>
        <div class="container">
          <div style="float:right;margin-left;30px;margin-top:10px;margin-right:156px;", class='col-lg-offset-0 col-lg-6 col-md-offset-0 col-md-8 col-sm-12 search-form'>
              <ul style="color:white;float:right;", class=" nav pull-right nav navbar-nav go-nav">
                <li class="active"><%= link_to "Home", root_path,style: "color:white" %></li>
                <% if current_user.present? %>
                <li><%= link_to 'Courses', courses_path,style: "color:white" %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete',style: "color:white" %></li>
                <% else %>

                <li><%= link_to 'SignIn', new_user_session_path,style: "color:white" %></li>
                <li><%= link_to 'SignUp', new_user_registration_path,style: "color:white" %></li>
                <% end %>
              </ul>
          </div>
        </div>
      </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edutest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: 'layouts/header' %>
  <div style="margin-top:55px; min-height:500px;" class="container-fluid well">
    <%= yield %>
  </div>
  <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/syllabuses/create.html.erb
<h1>Syllabuses#create</h1>
<p>Find me in app/views/syllabuses/create.html.erb</p>

app/views/syllabuses/index.html.erb
<div style="padding-top:20px;margin-left:183px;">
  <h2>Listing Syllabuses</h2><br /><br />
  <% if @syllabuses.present? %>
  <table>
    <tr>
      <th>Syllabus</th>
      <th>Links</th>
    </tr>

    <% @syllabuses.each do |syllabus| %>
      <tr>
        <td><%= syllabus.name %></td>
        <% if current_user.role == "professor" %>
          <td><%= link_to "Create Chapters", new_chapter_path(syllabus) %></td>
          <td><%= link_to "Show Chapter", chapters_path(syllabus) %></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </table><br />
  <% end %>
  <%= link_to 'Courses', courses_path, class: "btn btn-primary" %>
</div>